function C = get_C(t1,t2,t1_d,t2_d)
%get_C
%    C = get_C(T1,T2,T1_D,T2_D)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    17-Oct-2025 22:36:05

t4 = cos(t1);
t5 = cos(t2);
t6 = sin(t1);
t7 = sin(t2);
t8 = t4.*1.2e+1;
t9 = t6.*1.2e+1;
t10 = t4.*t5.*3.2e+1;
t11 = t4.*t7.*3.2e+1;
t12 = t5.*t6.*3.2e+1;
t13 = t6.*t7.*3.2e+1;
t14 = -t13;
t15 = t11+t12;
t16 = t10+t14;
t17 = t9+t15;
t18 = t8+t16;
t20 = t16.*t17.*(9.0./2.0);
t19 = t15.*t18.*(9.0./2.0);
t21 = -t20;
t22 = t19+t21;
t23 = t22.*t1_d.*2.0;
t24 = t22.*t2_d.*2.0;
t25 = -t24;
C = reshape([t25,t23,0.0,0.0,-t23+t25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,4]);
end
